### ISSUE TITLE
Is it possible to use your code to implement a terminal

### ISSUE THREAD

**Issue by shakfu** [jobor019/pyosc#2]
Hi jobor019,

Very cool project. I have my own little half-baked foray into the world of python3 - Max  (see https://github.com/shakfu/py-js)

In the above project, I implemented a python3 external in max that is supposed to allow the running of arbitrary python code in Max and also interop with max objects via cython wrapping of the max api (it was a lockdown project :-) 

I have a workable, but pre-alpha implementation where I can compile the external on a mac using the local (home-brew) python3.9 install.. I've been side tracked trying to build a fully static external with minimal dependencies (to enabled packaging in standalones) and which meet Apple's requirements (no fun whatsoever).

In any case, One of the thing that would be great is to see a is a kind of ipython-like interactive terminal which uses OSC can communicate with the python external in the above project. I suppose this would require a non-blocking setup on the terminal side. Would you have any thoughts on this?

Ian Duncan, author of scheme for max ( https://github.com/iainctduncan/scheme-for-max ) has a nice youtube video where he demos a similar concept using OSC to communicate to his scheme4max external ( https://www.youtube.com/watch?v=Wxfboeb7Jmw )

Anyway, just throwing it out there. It's great to see more activity linking python to max..

Thanks for sharing your project!

S

**Comment by jobor019** [comment]
Hi!

Nice project, it's a very welcome initiative! A good solution for max/python communication is something that's been missing in max for many years. Back in the python2 days the default solution was to use https://github.com/grrrr/py, but it was running on the macos system installation of python and as you're probably well aware of, required the user to recompile the external each time one wanted to change the interpreter. 

If I understand it correctly, when you say "a fully static external" you mean that the goal would be to embed a separate installation of python inside the external/max package rather than relying on the homebrew installation, right? One of the main issues we have on our team is how to distribute max packages relying on python to composers/non-developer users in a meaningful way (but no one really has the time to come up with a solution), so if that's what you're up to I'd love to help out in any way I can!

Either way, for your main question, I don't think this project will be of much help. This is really just a wrapper around the [python-osc](https://github.com/attwad/python-osc) to allow calling python functions from max in a max-friendly syntax with support for multidimensional lists, dictionaries, bach.llll's, a bit more elaborate but in nature not unlike what you already seem to have implemented to some extent.

If your goal is to communicate with the py object inside max from an editor outside max similar to the scheme4max video, I guess the easiest solution would be to just copy the solution in the video straight off by udpreceiving inside max and prepending an "exec", no? Of course that's perhaps not the most elegant solution. I guess that the main script running inside the python interpreter in your case is just continuously reading from stdin which it receives through the py object? If so, another possible approach would be to use an async OSC server to receive the messages from the external ipython environment in combination with an async stdin reader that reads the input received from max. I don't have any personal experience with using stdin and OSC in combination, but I've had great results from various combinations of async OSC servers, multiprocessing pipes and internal async scheduling in general so it's likely doable without too much hassle. Have a look at https://python-osc.readthedocs.io/en/latest/server.html#async-server and see if you can find some way to combine that with asyncio.stdin.

Hope that's of some help and good luck with your project!

**Comment by shakfu** [comment]
Thanks for your reply and good advice. 

> A good solution for max/python communication is something that's been missing in max for many years. Back in the python2 days the default solution was to use https://github.com/grrrr/py, but it was running on the macos system installation of python and as you're probably well aware of, required the user to recompile the external each time one wanted to change the interpreter.

I was aware of https://github.com/grrrr/py but it was python2.7 only at the time which was a deal-breaker. I believe it has undergone some recent development which may mean that it works in python3, but I haven't see this in action.

Incidentally, the current implementation of `py-js` also requires the user to rebuild the external when there is a major change to the interpreter version (as in a change from 3.8 to 3.9 for example but not from 3.9 to 3.9.1). This is not such a big deal since such transitions are quite smooth, but it's known tradeoff if you want your external to track your home-brew python version and benefit from access to all the installed packages in your `/usr/local/lib/python3.9/site-packages`.

> If I understand it correctly, when you say "a fully static external" you mean that the goal would be to embed a separate installation of python inside the external/max package rather than relying on the homebrew installation, right? One of the main issues we have on our team is how to distribute max packages relying on python to composers/non-developer users in a meaningful way (but no one really has the time to come up with a solution), so if that's what you're up to I'd love to help out in any way I can!

Your understanding is correct. In fact, I was try to implement three deployment scenarios, 

1. max externals linked to the home-brew installed python3
2. python-in-a-max-package: a full python3 installation embedded in a max package with its related externals
3. python-in-a-max-external: where the full python interpreter is statically linked to the external, and the python standard library is zipped and included in the external bundle.

The current implementation works in the 1st scenario and with some mixed success in the others: In the 2nd case, it did not work for max standalones in some prior versions of Max which led me to defer this method and focus on the 3rd method. In this case, the requirement to resolve the Apple code signing issues, statically link as many of the dynamic library dependencies into the external as possible, while minimizing the footprint of the python installation itself was quite a rabbit hole and indeed a project in of itself. It led me to experiment widely which is evident in the current code-base, but I reached a point where I had some rudimentary proof-of-concept which successfully embedded python in an external and which worked in the standalone deployment case.

I had to pause the project since then due to life and work resuming from lockdown, but I have kept the 1st deployment case working with the current version of home-brew python, and since then have worked a bit one the offshoot project now in a new GitHub project ( https://github.com/shakfu/pybuild ) which has a script to automatically download and build python statically and minimally (also for shared and framework flavors which are suitable for the package deployment scenarios). It currently and promisingly delivers a static build which has not overt dynamic dependencies which should work well in the 3rd deployment scenarios. Just have to bring this code back into the main project at some point and clean up the build system.

If you would like to check out the code, my advice would be try to get the home-brew version working on your system  (https://github.com/shakfu/py-js) and get a feel for working with this and understanding its limitations. If you are still interested in embedded python then clone (https://github.com/shakfu/pybuild) and run `python3 pybuild.py static --install` in its directory, and it will download python3.9 from python.org and its dependencies and build the a static python build. The eventual idea is to use the libpython.a that comes out of this to instead build the max external in the other project. If one keeps the standard library in the 'Resources' directory and code signing is correctly done then this should theoretically deliver the 3rd deployment case: the reproducible nirvana of python-embedded in a max standalone. So all in all not unachievable, but requires time. Your collaboration and feedback would be welcome in all cases.

S

**Comment by shakfu** [comment]
Hi,

Just following on from above, I've largely figured out the major blocking issues (packaging max/python into max packages into standalones and packaging into externals). If you are interested check https://github.com/shakfu/py-js) and let me know if you have any issues.

s

**Comment by jobor019** [comment]
Hi!

Great work! I'm sorry for my lack of response the past months, it's been a very busy period, but I've had a brief look at your project in the past few days!

I tested your application briefly already back in February and managed to get it working quite nicely. This time, I took the longer route and had a deeper look at your code (and other random things, such as reading through all your dev notes - I'm easily distracted). I was particularly interested in how you're building the contained python library (I guess your solution to some extent stems from [this blog post](https://joaoventura.net/blog/2016/embeddable-python-osx/)?), I've previously been experimenting with Pyinstaller and py2app but the issue here is how to properly embed them in an external, as I saw you already had an open issue regarding on py2app.

I noticed quite a few issues in the build scripts regarding word splitting and possibly dangerous expansions - in fact the first command issued when running `make -C source/py bin-homebrew-pkg` is split into `rm -rf ~/Documents/Max` if you're developing in `~/Documents/Max\ 8/Packages`, which isn't exactly ideal if you also have a Max 6 or older installation. I did some cleaning here and managed to get a working self-contained python that indeed could run on a virtual machine without python installed. Most of the cleaning was just temporary quick fixes, but if you want I could fix it up a bit and make a proper PR?

I didn't finish this path, but rather did some testing with the default `py` object (`make -C source/py build`), among other things the numpy issues you mentioned in your notes. I got this error before crashing:
```
[py __main__] exec import numpy as np; x=np.arange(20): SystemError('Objects/structseq.c:401: bad argument to internal function')
```
I doubt this is of much help since it's probably running in a different thread meaning that you can't catch it? Either way, if you have any more info regarding this issue I'd be happy to look into it further. The flag solution you suggested in your notes might be one way to solve it, but I really hope there's a more convenient way to handle this - I don't think that for example [pyext](https://github.com/grrrr/py) has this issue (though I could be wrong, and I really don't either of your code bases well enough right now, nor whether this is an issue specifically related to python 3).

Another thing of importance is the fact that the object blocks the ui thread. Try for example `exec "import time; time.sleep(5)"` - Max will freeze for 5 seconds. This particular case is kind of niche, but even if there are micro-freezes of a couple of milliseconds, these could still mean that the ui is unavailable during that particular time and any user interaction won't be registered. I really don't remember how the interaction between different threads work under the hood in max and it's been a long time since I've written an external so I don't have an idea of a solution right now, but I think this will be very important to solve. What I do know is that you really don't want to go down the asynchronous route, i.e. that the object evaluates the function and then returns the result whenever finished. This is exactly what I'm doing in this repo and exactly why I in each application using this have to implement messy workarounds to handle initialization of objects. You really want this type of case to really behave synchronous (but without blocking the ui thread) or it will break all scaleability of the system:
![image](https://user-images.githubusercontent.com/28217154/114317395-2ce23d00-9b08-11eb-872c-ab718cc40835.png)

I'd be interested to hear about your long term plan with this project, what the current issues are and what you're working on right now. As I've realized since your last post, I don't really have as much time to spare as I originally thought, but I'd be happy to help out with implementing specific tasks or discussing implementation/design decisions. Although, I don't think this issue (or repository) is the place to do it, so what would be your preferred means of communication? A global "issue" in your repo much like this one? Task-specific issues in your repo? Mail? Other?

Either way, really nice work! I'm really looking forward to the results of this!

**Comment by shakfu** [comment]
Hi,

Thanks very much for the detailed feedback. In fact I think you are first one to give the project a real shake and provide practical comments. Very much appreciated.

> I tested your application briefly already back in February and managed to get it working quite nicely. This time, I took the longer route and had a deeper look at your code (and other random things, such as reading through all your dev notes - I'm easily distracted). I was particularly interested in how you're building the contained python library (I guess your solution to some extent stems from this blog post?), I've previously been experimenting with Pyinstaller and py2app but the issue here is how to properly embed them in an external, as I saw you already had an open issue regarding on py2app.

Correct. I was inspired by that blog post to try to re-use homebrew python which seemed to be used pervasively among Mac users instead of the system python which is to be avoided.

So out of the now four methods that currently work, three are derived from repackaging homebrew python, and the fourth, using statically built self-contained externals, is built from source.

I painfully discovered that in certain cases, I could get a method to work in Max, but then fail the code-signing step because of a 'illformed bundle' error which provided no further details on how to make it 'well-formed'. I tried to figure out what was the issue and didn't really learn much from py2app or pyInstaller. The Aha moment came from discovering the [briefcase project](https://github.com/beeware/briefcase) which addressed my use-case exactly. The big discovery there was that I had to put pythonhome somewhere in the `Resources` folder of the bundle for it to work, and also how to craft a minimal statically built `libpythonx.y.a`.

> I noticed quite a few issues in the build scripts regarding word splitting and possibly dangerous expansions - in fact the first command issued when running make -C source/py bin-homebrew-pkg is split into rm -rf ~/Documents/Max if you're developing in ~/Documents/Max\ 8/Packages, which isn't exactly ideal if you also have a Max 6 or older installation. I did some cleaning here and managed to get a working self-contained python that indeed could run on a virtual machine without python installed. Most of the cleaning was just temporary quick fixes, but if you want I could fix it up a bit and make a proper PR?

Thanks for spending some real time testing the system and also for highlighting some major risk areas. Unfortunately I've neglected the Makefile/Bash build scripts recently because I have been so busy developing the alternative python build system. You are literally the first person to review the code. Any feedback, or comments whatsoever are just great. A PR would be great naturally.

>I didn't finish this path, but rather did some testing with the default py object (make -C source/py build), among other things the numpy issues you mentioned in your notes. I got this error before crashing:
> [py __main__] exec import numpy as np; x=np.arange(20): SystemError('Objects/structseq.c:401: bad argument to internal function')

This error is a result of not closing and then restarting Max after a session which imported `numpy`.  You can see it quite clearly in `test_numpy.maxpat`. If you try it again after a close Max / restart step then the problem goes away. Still, you have found one of the more problematic areas: making `numpy` work well is a project in itself: for example, conversion of `numpy` types, etc..

> I doubt this is of much help since it's probably running in a different thread meaning that you can't catch it? Either way, if you have any more info regarding this issue I'd be happy to look into it further. The flag solution you suggested in your notes might be one way to solve it, but I really hope there's a more convenient way to handle this - I don't think that for example pyext has this issue (though I could be wrong, and I really don't either of your code bases well enough right now, nor whether this is an issue specifically related to python 3).

It's really another manifestation of python not yet being able to cleanly unload and reload c-extensions. It can't be helped except to restart Max unfortunately -- which is all the more reason to stay in pure python.

> Another thing of importance is the fact that the object blocks the ui thread. Try for example exec "import time; time.sleep(5)" - Max will freeze for 5 seconds. This particular case is kind of niche, but even if there are micro-freezes of a couple of milliseconds, these could still mean that the ui is unavailable during that particular time and any user interaction won't be registered. I really don't remember how the interaction between different threads work under the hood in max and it's been a long time since I've written an external so I don't have an idea of a solution right now, but I think this will be very important to solve. What I do know is that you really don't want to go down the asynchronous route, i.e. that the object evaluates the function and then returns the result whenever finished. This is exactly what I'm doing in this repo and exactly why I in each application using this have to implement messy workarounds to handle initialization of objects. You really want this type of case to really behave synchronous (but without blocking the ui thread) or it will break all scaleability of the system:

Thank you for raising this issue. Honestly I hadn't noticed it, since I always assumed that python would not be used for anything time sensitive, but the blocking of Max is definitely problematic, but conceivably solvable since there has been no effort yet to run python in its own thread.

>I'd be interested to hear about your long term plan with this project, what the current issues are and what you're working on right now. As I've realized since your last post, I don't really have as much time to spare as I originally thought, but I'd be happy to help out with implementing specific tasks or discussing implementation/design decisions. Although, I don't think this issue (or repository) is the place to do it, so what would be your preferred means of communication? A global "issue" in your repo much like this one? Task-specific issues in your repo? Mail? Other?

All good questions. Naturally, in the short to medium term, I'd like to get this project useful and stable enough to be used in a real project, and then iterate based on practical feedback and get it ready for some kind of release which should have properly signed externals or a package which can be used in a standalone. But it's a slow experimental burn right now, with no pressure, no urgency, no deadlines. Feel free to drop in or otherwise. It's all good.

As an aside, I'm less optimistic that the intractable issues such as c-extension reloading will get fixed any time soon, and I would like to also experiment, if time permits, with some alternative models: for example I'm drawn to the idea of a zeromq and translation layer external for Max which could talk to any language and be one step closer to an ipython/jupyter-type kernel.

In any case, I agree that this repo is not the place to continue discussion. I suggest to post any way you like on the project's repo or alternatively for anything offline you can reach me via email -- first . last @ gmail.com 

> Either way, really nice work! I'm really looking forward to the results of this!

Likewise. I've enjoyed our discussion and really appreciate your interest in the project.

S

**Comment by shakfu** [comment]
Speaking of the devil: I just found this which confirms the issues with numpy and reloading: https://community.vcvrack.com/t/blowing-the-dust-off-python-in-prototype/12909
